# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

apt_packages:
  - libv8-dev

before_install:
  - sudo apt-get install -y libv8-dev
